apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-postgres-init
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  inventory.sql: {{ .Values.postgresInit.inventorySql | toYaml | indent 1 }}
