apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-superset
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.superset.replicas }}
  selector:
    matchLabels:
      app: superset
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: superset
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: SUPERSET_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: superset-secret
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.superset.superset.image.repository }}:{{ .Values.superset.superset.image.tag
          | default .Chart.AppVersion }}
        name: superset
        ports:
        - containerPort: 8088
          name: superset
        resources: {}
