apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-postgres
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.type }}
  selector:
    app: postgres
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.postgres.ports | toYaml | nindent 2 -}}
